"""
app.py — Insurance Premium Predictor
IS 4007 | Statistics in Practice II
Pasindu Jayasundara | s16806

Run with: streamlit run app.py
Requires: model.pkl (generated by train_model.py) in the same folder
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# ── Page config ────────────────────────────────────────────────
st.set_page_config(
    page_title="Insurance Premium Predictor",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# ── Styling ────────────────────────────────────────────────────
st.markdown("""
<style>
    .stApp { background-color: #F4F6FA; }
    #MainMenu, footer, header { visibility: hidden; }

    .top-banner {
        background: linear-gradient(135deg, #1B3A6B 0%, #2563EB 100%);
        padding: 28px 36px;
        border-radius: 12px;
        margin-bottom: 28px;
    }
    .top-banner h1 { color: white; font-size: 1.9rem; font-weight: 700; margin: 0 0 6px 0; }
    .top-banner p  { color: #C7D9F5; font-size: 0.92rem; margin: 0; }

    .card {
        background: white;
        border-radius: 10px;
        padding: 24px 28px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.07);
        margin-bottom: 18px;
    }
    .card-title {
        font-size: 0.78rem;
        font-weight: 700;
        color: #6B7280;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        margin-bottom: 16px;
    }

    .premium-box {
        background: linear-gradient(135deg, #1B3A6B 0%, #2563EB 100%);
        border-radius: 12px;
        padding: 28px;
        text-align: center;
        margin-bottom: 16px;
    }
    .premium-label  { color: #C7D9F5; font-size: 0.82rem; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase; margin-bottom: 8px; }
    .premium-amount { color: white; font-size: 2.8rem; font-weight: 800; line-height: 1; margin-bottom: 4px; }
    .premium-sub    { color: #93C5FD; font-size: 0.85rem; }

    .monthly-box {
        background: #EFF6FF;
        border: 1px solid #BFDBFE;
        border-radius: 10px;
        padding: 18px 24px;
        text-align: center;
        margin-bottom: 16px;
    }
    .monthly-label  { color: #3B82F6; font-size: 0.8rem; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; }
    .monthly-amount { color: #1B3A6B; font-size: 2rem; font-weight: 700; }

    .risk-low    { background:#D1FAE5; color:#065F46; border:1px solid #6EE7B7; }
    .risk-medium { background:#FEF3C7; color:#92400E; border:1px solid #FCD34D; }
    .risk-high   { background:#FEE2E2; color:#991B1B; border:1px solid #FCA5A5; }
    .risk-badge  { border-radius: 8px; padding: 12px 18px; font-size: 0.9rem; font-weight: 600; text-align: center; margin-bottom: 16px; }

    .profile-row {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 9px 0;
        border-bottom: 1px solid #F3F4F6;
        font-size: 0.88rem;
    }
    .profile-row:last-child { border-bottom: none; }
    .profile-key   { color: #6B7280; font-weight: 500; }
    .profile-value { color: #111827; font-weight: 600; }

    .stButton > button {
        background: linear-gradient(135deg, #1B3A6B, #2563EB) !important;
        color: white !important;
        border: none !important;
        border-radius: 8px !important;
        padding: 14px 24px !important;
        font-size: 1rem !important;
        font-weight: 700 !important;
        width: 100% !important;
    }

    .section-label {
        color: #1B3A6B;
        font-size: 1rem;
        font-weight: 700;
        margin-bottom: 14px;
        padding-bottom: 8px;
        border-bottom: 2px solid #DBEAFE;
    }

    .footer {
        text-align: center;
        color: #9CA3AF;
        font-size: 0.78rem;
        margin-top: 24px;
        padding: 16px;
        border-top: 1px solid #E5E7EB;
    }
</style>
""", unsafe_allow_html=True)


# ── Load model ─────────────────────────────────────────────────
FEATURE_COLS = ['age', 'sex', 'bmi', 'children', 'smoker',
                'region_northeast', 'region_northwest',
                'region_southeast', 'region_southwest',
                'smoker_bmi']

@st.cache_resource
def load_model():
    data = joblib.load('MIPML.pkl')
    if isinstance(data, dict):
        return data['model'], data.get('features', FEATURE_COLS)
    return data, FEATURE_COLS

try:
    model, FEATURE_COLS = load_model()
    model_loaded = True
except FileNotFoundError:
    model_loaded = False




# ── Helpers ────────────────────────────────────────────────────
def build_features(age, sex, bmi, children, smoker, region):
    sex_enc    = 1.0 if sex    == 'Male' else 0.0
    smoker_enc = 1.0 if smoker == 'Yes'  else 0.0
    row = {
        'age'              : age,
        'sex'              : sex_enc,
        'bmi'              : bmi,
        'children'         : children,
        'smoker'           : smoker_enc,
        'region_northeast' : 1.0 if region == 'Northeast' else 0.0,
        'region_northwest' : 1.0 if region == 'Northwest' else 0.0,
        'region_southeast' : 1.0 if region == 'Southeast' else 0.0,
        'region_southwest' : 1.0 if region == 'Southwest' else 0.0,
        'smoker_bmi'       : smoker_enc * bmi,
    }
    return pd.DataFrame([row])[FEATURE_COLS]

def bmi_category(bmi):
    if bmi < 18.5: return "Underweight"
    elif bmi < 25: return "Normal weight"
    elif bmi < 30: return "Overweight"
    else:          return "Obese"

def get_risk(charge, smoker, bmi):
    if charge > 30000 or (smoker == 'Yes' and bmi >= 30):
        return 'High',   'risk-high',   '⚠️  High Risk'
    elif charge > 15000 or smoker == 'Yes' or bmi >= 30:
        return 'Medium', 'risk-medium', '⚡  Moderate Risk'
    else:
        return 'Low',    'risk-low',    '✅  Low Risk'


# ══════════════════════════════════════════════════════════════
#  LAYOUT
# ══════════════════════════════════════════════════════════════

st.markdown("""
<div class="top-banner">
    <h1>🏥 Insurance Premium Predictor</h1>
    <p>Get an instant estimate of your annual medical insurance premium</p>
</div>
""", unsafe_allow_html=True)

if not model_loaded:
    st.error("⚠️ **MIPML.pkl not found.** Please make sure MIPML.pkl is in the same folder as app.py, then restart the app.")
    st.stop()

left_col, right_col = st.columns([1, 1], gap="large")

# ── LEFT: Input ────────────────────────────────────────────────
with left_col:
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.markdown('<div class="section-label">📋 Enter Your Details</div>', unsafe_allow_html=True)

    age      = st.slider("Age", min_value=5, max_value=120, value=30)
    c1, c2   = st.columns(2)
    with c1:
        sex    = st.selectbox("Sex", ["Male", "Female"])
    with c2:
        smoker = st.selectbox("Smoker", ["No", "Yes"])

    bmi = st.number_input("BMI (Body Mass Index)", min_value=5.0,
                          max_value=70.0, value=28.0, step=0.1, format="%.1f")
    bmi_cat = bmi_category(bmi)
    st.caption(f"WHO classification: **{bmi_cat}**")

    c3, c4 = st.columns(2)
    with c3:
        children = st.selectbox("No. of Children", [0, 1, 2, 3, 4, 5])
    with c4:
        region = st.selectbox("Region", ["Northeast", "Northwest", "Southeast", "Southwest"])

    st.markdown("<br>", unsafe_allow_html=True)
    predict_clicked = st.button("🔍 Predict My Premium")
    st.markdown('</div>', unsafe_allow_html=True)




# ── RIGHT: Results ─────────────────────────────────────────────
with right_col:
    if predict_clicked:
        X_input    = build_features(age, sex, bmi, children, smoker, region)
        prediction = float(model.predict(X_input)[0])
        monthly    = prediction / 12
        risk_level, risk_class, risk_label = get_risk(prediction, smoker, bmi)

        st.markdown(f"""
        <div class="premium-box">
            <div class="premium-label">Estimated Annual Premium</div>
            <div class="premium-amount">${prediction:,.2f}</div>
            <div class="premium-sub">United States Insurance Market</div>
        </div>
        """, unsafe_allow_html=True)

        st.markdown(f"""
        <div class="monthly-box">
            <div class="monthly-label">Monthly Equivalent</div>
            <div class="monthly-amount">
                ${monthly:,.2f}
                <span style="font-size:1rem; color:#6B7280;">/ month</span>
            </div>
        </div>
        """, unsafe_allow_html=True)

        st.markdown(f"""
        <div class="risk-badge {risk_class}">{risk_label}</div>
        """, unsafe_allow_html=True)

        st.markdown('<div class="card">', unsafe_allow_html=True)
        st.markdown('<div class="card-title">Profile Summary</div>', unsafe_allow_html=True)

        rows = [
            ("Age",             f"{age} years"),
            ("Sex",             sex),
            ("BMI",             f"{bmi:.1f} kg/m²  ({bmi_cat})"),
            ("Children",        str(children)),
            ("Smoker",          smoker),
            ("Region",          region),
            ("Annual Premium",  f"${prediction:,.2f}"),
            ("Monthly Premium", f"${monthly:,.2f}"),
            ("Risk Level",      risk_level),
        ]
        for key, val in rows:
            col_val = "#1B3A6B" if "Premium" in key else "#111827"
            st.markdown(f"""
            <div class="profile-row">
                <span class="profile-key">{key}</span>
                <span class="profile-value" style="color:{col_val};">{val}</span>
            </div>""", unsafe_allow_html=True)

        st.markdown('</div>', unsafe_allow_html=True)

        if risk_level == 'High':
            st.info("💡 **Tip:** Smoking and high BMI are the strongest cost drivers. "
                    "Quitting smoking or reducing BMI can significantly lower your premium.")
        elif risk_level == 'Medium':
            st.info("💡 **Tip:** Your premium is moderate. Lifestyle changes "
                    "such as BMI management could reduce costs.")
        else:
            st.success("✅ **Great profile!** You are in the lower-risk category. "
                       "Maintaining a healthy lifestyle keeps your premium low.")

    else:
        st.markdown("""
        <div class="card" style="text-align:center; padding:60px 28px;">
            <div style="font-size:3.5rem; margin-bottom:18px;">🏥</div>
            <div style="font-size:1.1rem; color:#1B3A6B; font-weight:700; margin-bottom:10px;">
                Your premium will appear here
            </div>
            <div style="font-size:0.88rem; color:#6B7280; line-height:1.6;">
                Fill in your details on the left<br>and click
                <b>Predict My Premium</b> to see your estimate.
            </div>
        </div>
        """, unsafe_allow_html=True)